### ISSUE TITLE
Ensure space between curly braces

### ISSUE THREAD

**Issue by alisahq** [Mar1789/Mentorship-Capstone-Project#3]
https://github.com/Mar1789/Mentorship-Capstone-Project/blob/a39cd68a3caa7f0105bcbf152df36ee2b62f74fc/Back-end/auth.js#L97

Please leave spaces between the curly braces in the code.

**Comment by Mar1789** [comment]
So in this example, it should be: 
} 
else { 

Let me know if I misunderstood so I can fix it in my code.

**Comment by alisahq** [comment]
Yes. You may also download any VS code auto-format related extensions to have your code automatically formatted.
