### ISSUE TITLE
Remove console.log as debugging purpose

### ISSUE THREAD

**Issue by alisahq** [Mar1789/Mentorship-Capstone-Project#5]
https://github.com/Mar1789/Mentorship-Capstone-Project/blob/a39cd68a3caa7f0105bcbf152df36ee2b62f74fc/Back-end/index.js#L17-L18

Usually console.log is used for debugging purpose. Please ensure these got removed before pushing to prod.

**Comment by Mar1789** [comment]
Shouldn't line 18 be kept in Github since it is just saying that the server is running in case an error occurs? I removed line 17 from my code.

**Comment by alisahq** [comment]
Could you close all tickets if you are done?

**Comment by Mar1789** [comment]
Yep! Sorry about that
