### ISSUE TITLE
prisma query

### ISSUE THREAD

**Issue by jialic2** [Mar1789/Mentorship-Capstone-Project#8]
https://github.com/Mar1789/Mentorship-Capstone-Project/blob/c5f88f3f5a47d2d5c5aab9f90478e50b5b582bae/Back-end/index.js#L25-L28

Just curious, seems like there are 2 ways of specifying field == some value in prisma query, are these 2 ways equivalent? I feel we probably can stick to 1 way to keep the code consistent.

**Comment by Mar1789** [comment]
Correct. I was having an issue where my prisma was giving me an error and I was trying to find a way to debug it (forgot to do npx prisma generate where it restablishes the link between the database and backend after a schema migration). I can update it for consistency. Sorry about that.

**Comment by Mar1789** [comment]
Updated! Will be closing the issue ticket now.
